from fastapi.responses import HTMLResponse

DASHBOARD_HTML = """
<!doctype html><html><head><title>APEX v5.2 Dashboard</title><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>
body{margin:0;background:#070b16;color:#e5e7eb;font-family:Inter,Arial,sans-serif}.wrap{max-width:1450px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:14px}.brand h1{margin:0;font-size:30px}.muted{color:#9ca3af}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:18px 0}.card{background:linear-gradient(180deg,#111827,#0b1220);border:1px solid #1f2937;border-radius:20px;padding:18px;box-shadow:0 20px 50px rgba(0,0,0,.25)}.big{font-size:30px;font-weight:800;margin-top:6px}.good{color:#22c55e}.bad{color:#ef4444}.warn{color:#f59e0b}.pill{display:inline-flex;align-items:center;gap:8px;padding:9px 13px;border-radius:999px;background:#111827;border:1px solid #243047;color:#93c5fd}button{background:#2563eb;color:#fff;border:0;border-radius:12px;padding:12px 15px;font-weight:700;cursor:pointer}button.secondary{background:#1f2937}.wide{grid-column:span 2}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #1f2937;padding:10px;text-align:left;font-size:13px}pre{white-space:pre-wrap;background:#020617;border:1px solid #1f2937;border-radius:14px;padding:12px;max-height:280px;overflow:auto}.nav{display:flex;gap:10px;flex-wrap:wrap}.nav a{color:#c7d2fe;text-decoration:none;background:#111827;border:1px solid #1f2937;padding:10px 12px;border-radius:12px}@media(max-width:1000px){.grid{grid-template-columns:1fr}.wide{grid-column:span 1}.top{display:block}.nav{margin-top:14px}}
</style></head><body><div class="wrap"><div class="top"><div class="brand"><h1>APEX v5.2 Trading Dashboard</h1><div class="muted">Paper trading, exchange status, PnL, equity curve and live controls.</div></div><div class="nav"><a href="/admin">Admin</a><a href="/docs">Docs</a><a href="/health">Health</a><button onclick="scan()">Run Scan</button></div></div><div style="margin-top:14px"><span id="mode" class="pill">MODE: Loading...</span> <span id="exchange" class="pill">Exchange: Loading...</span></div><div class="grid"><div class="card"><div class="muted">Equity</div><div class="big" id="equity">$0</div></div><div class="card"><div class="muted">Total PnL</div><div class="big" id="pnl">$0</div></div><div class="card"><div class="muted">Win Rate</div><div class="big" id="winrate">0%</div></div><div class="card"><div class="muted">Open Trades</div><div class="big" id="open">0</div></div><div class="card wide"><h2>Equity Curve</h2><canvas id="curve" height="120"></canvas></div><div class="card wide"><h2>System Status</h2><pre id="status">Loading...</pre></div><div class="card wide"><h2>Paper Trades</h2><table><thead><tr><th>ID</th><th>Exchange</th><th>Pair</th><th>Side</th><th>Status</th><th>Entry</th><th>SL</th><th>TP1</th><th>PnL</th><th>Reason</th></tr></thead><tbody id="trades"></tbody></table></div><div class="card wide"><h2>Last Scan</h2><pre id="lastscan">No scan yet.</pre></div></div></div><script>
let chart;async function j(u,o){let r=await fetch(u,o);return await r.json()}async function load(){let s=await j('/api/dashboard/summary');let cfg=await j('/api/config');let health=await j('/health');let admin={};try{admin=await j('/api/admin/settings')}catch(e){}document.getElementById('mode').textContent='MODE: '+((admin.exchange?.trading_mode||'paper').toUpperCase());document.getElementById('exchange').textContent='Exchange: '+(cfg.exchange||health.exchange||'unknown');document.getElementById('equity').textContent='$'+s.equity;document.getElementById('pnl').textContent='$'+s.total_pnl;document.getElementById('pnl').className='big '+(s.total_pnl>=0?'good':'bad');document.getElementById('winrate').textContent=s.win_rate+'%';document.getElementById('open').textContent=s.open_trades;document.getElementById('status').textContent=JSON.stringify({health,cfg,admin_mode:admin.exchange?.trading_mode||'paper'},null,2);let labels=s.equity_curve.map(x=>x.trade),data=s.equity_curve.map(x=>x.equity);if(chart)chart.destroy();chart=new Chart(document.getElementById('curve'),{type:'line',data:{labels,datasets:[{label:'Equity',data,tension:.35}]},options:{plugins:{legend:{labels:{color:'#e5e7eb'}}},scales:{x:{ticks:{color:'#9ca3af'}},y:{ticks:{color:'#9ca3af'}}}}});let trades=await j('/api/paper-trades');document.getElementById('trades').innerHTML=trades.map(t=>`<tr><td>${t.id}</td><td>${t.exchange}</td><td>${t.pair}</td><td>${t.direction}</td><td>${t.status}</td><td>${Number(t.entry).toFixed(4)}</td><td>${Number(t.stop_loss).toFixed(4)}</td><td>${Number(t.tp1).toFixed(4)}</td><td class="${t.pnl_usd>=0?'good':'bad'}">$${Number(t.pnl_usd).toFixed(2)}</td><td>${t.close_reason||''}</td></tr>`).join('')||'<tr><td colspan="10" class="muted">No paper trades yet. Use admin/test mode or wait for a signal.</td></tr>'}async function scan(){document.getElementById('lastscan').textContent='Scanning...';let r=await j('/api/scan-once',{method:'POST'});document.getElementById('lastscan').textContent=JSON.stringify(r,null,2);load()}load();setInterval(load,10000)
</script></body></html>
"""

def dashboard_page():
    return HTMLResponse(DASHBOARD_HTML)
